config/routes.rb
Freal::Application.routes.draw do

  get "cities/index"

  get "stations/index"

  get "owners/index"

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users
  
  namespace :admin do
    resources :counties
    resources :municipalities do
      member do
        get :cities
      end
    end
    resources :cities
    match "all_stations" => "stations#index", :as => :all_stations
    match "all_owners" => "owners#index", :as => :all_owners
  end
  
  namespace :api do
    namespace :v1 do
      get '/counties'   => 'counties#all', format: :json
      get '/cities/all/:page'   => 'cities#all', format: :json, conditions: {page: /\d+/}
      get '/cities/find/:query' => 'cities#find_by_name', format: :json
      get '/cities/ac/:query' => 'cities#autocomplete', format: :json
      get '/county/:id/municipalities' => 'counties#municipalities', format: :json
      
      delete '/myfavorites/:token/:id' => 'cities#delete_favorite', format: :json
      
      match '/nearme'   => 'cities#nearme', format: :json
      get '/mystation/:token/:id' => 'cities#mystation', format: :json#, :constraints => {:token => /[0-9a-f]{64}/}
      get '/myfavorites/:token' => 'cities#myfavorites', format: :json#, :constraints => {:token => /[0-9a-f]{64}/}
      post '/register_device/:token' => 'registration#create', format: :json#, :constraints => {:token => /[0-9a-f]{64}/}
      post '/observe_station/:token/:station_id' => 'registration#observe_station', format: :json, :constraints => {:token => /[0-9a-f]{64}/}
    end  
  end
end

app/models/county.rb
class County
  include Mongoid::Document
  include Mongoid::Timestamps
  paginates_per 10
  AREA_CODES = {'1' => 'Attica', '2' => 'Thessaloniki', '3' => 'Other Greece'}
  field :name
  field :code
  field :area, :type => Integer, :default => 0
  has_many :municipalities, dependent: :delete
  
  def api_attributes
    data = {}
    attributes.select{|k,v| %w(_id name code area).include?(k)}.each do |k, v|
      data[k] = v.to_s.strip
    end
    data
  end
end

app/controllers/admin/counties_controller.rb
class Admin::CountiesController < Admin::ManageController
  def index
    @page = params[:page]
    @page ||= 1
    @page = @page.to_i
    @counties = County.all.asc(:name).page(@page)
  end
  
  def show
    @county = County.find(params[:id])
    @muns = @county.municipalities
  end
end

app/controllers/api/v1/counties_controller.rb
class Api::V1::CountiesController < Api::V1::BaseController
  
  def all
    counties = County.all.asc(:name).collect{|i| i.api_attributes}
    respond_with(counties: counties)
  end

  def municipalities
    county = County.find(params[:id])
    municipalities = county.municipalities.all.asc(:name)
    values = municipalities.collect{|i| i.api_attributes}
    respond_with(county: county.api_attributes, municipalities: values)
  end
  
end

app/helpers/admin/counties_helper.rb
module Admin::CountiesHelper
end

app/helpers/api/v1/counties_helper.rb
module Api::V1::CountiesHelper
end

app/views/admin/counties/_county.html.haml
%tr
  %td
    =link_to county.name, admin_county_path(county)
    %br
    %span=county.municipalities.count
    %span Δήμοι
  

app/views/admin/counties/_municipals.html.haml
%table.table.table-striped
  %ul.unstyled
    -municipals.each_with_index do |mun, index|
      %li
        %strong=index + 1 
        %span . 
        %span= link_to mun.name, mun.url_for_fueltype
        %em="(#{mun.code})"
        %span=link_to "#{mun.cities.count} Πόλεις(-η)", cities_admin_municipality_url(mun.id), :remote => true
        #cities{:id=>mun.id}
        -Station::FUEL_TYPES.each do |k, v|
          %span=link_to "#{v} |", mun.url_for_fueltype(k.to_i)
   
      %hr

app/views/admin/counties/index.html.haml
%table.table.table-striped
  %caption 
    %h3 Νομοί
  =render :partial => 'county', :collection => @counties
%p=paginate @counties

app/views/admin/counties/show.html.haml
%h3=@county.name
%span Κωδικός
%strong=@county.code
%br
%span Δήμοι
%span="(#{@muns.count})"
%hr
=render :partial => 'municipals', :object => @muns.sort{|a,b| a.name <=> b.name}