config/routes.rb
Freal::Application.routes.draw do

  get "cities/index"

  get "stations/index"

  get "owners/index"

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users
  
  namespace :admin do
    resources :counties
    resources :municipalities do
      member do
        get :cities
      end
    end
    resources :cities
    match "all_stations" => "stations#index", :as => :all_stations
    match "all_owners" => "owners#index", :as => :all_owners
  end
  
  namespace :api do
    namespace :v1 do
      get '/counties'   => 'counties#all', format: :json
      get '/cities/all/:page'   => 'cities#all', format: :json, conditions: {page: /\d+/}
      get '/cities/find/:query' => 'cities#find_by_name', format: :json
      get '/cities/ac/:query' => 'cities#autocomplete', format: :json
      get '/county/:id/municipalities' => 'counties#municipalities', format: :json
      
      delete '/myfavorites/:token/:id' => 'cities#delete_favorite', format: :json
      
      match '/nearme'   => 'cities#nearme', format: :json
      get '/mystation/:token/:id' => 'cities#mystation', format: :json#, :constraints => {:token => /[0-9a-f]{64}/}
      get '/myfavorites/:token' => 'cities#myfavorites', format: :json#, :constraints => {:token => /[0-9a-f]{64}/}
      post '/register_device/:token' => 'registration#create', format: :json#, :constraints => {:token => /[0-9a-f]{64}/}
      post '/observe_station/:token/:station_id' => 'registration#observe_station', format: :json, :constraints => {:token => /[0-9a-f]{64}/}
    end  
  end
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Freal", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Freal"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag 'gmaps4rails'
    
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Fuel Prices
          -if user_signed_in?
            .container.nav-collapse
              %ul.nav
                %li.dropdown
                  =link_to '#', {:class=>'dropdown-toggle', 'data-toggle'=>'dropdown'} do 
                    Location
                    %b.caret
                  %ul.dropdown-menu
                    %li=link_to "Regions", admin_counties_path
                    %li=link_to "Municipals", admin_municipalities_path
                    %li=link_to "Cities", admin_cities_path
                %li.dropdown
                  =link_to '#', {:class=>'dropdown-toggle', 'data-toggle'=>'dropdown'} do 
                    Fuel
                    %b.caret
                  %ul.dropdown-menu
                    %li=link_to "Owners", admin_all_owners_path
                    %li=link_to "Stations", admin_all_stations_path
              %ul.nav.pull-right
                %li=link_to 'Logout', destroy_user_session_url, :method => :delete

    .container-fluid

      .row-fluid
        / .span3
        /   .well.sidebar-nav
        /     %ul.nav.nav-list
        /       %li.nav-header Sidebar
        /       %li= link_to "Link 1", "/path1"
        /       %li= link_to "Link 2", "/path2"
        /       %li= link_to "Link 3", "/path3"
        .span9
          = bootstrap_flash
          = yield
    
      / %footer
      /   %p &copy; Company 2013